dist: bionic
language: python
git:
  depth: 2
python:
  - "2.7"
  - "3.7"
  - "3.8"
matrix:
  include:
    python: "3.7"
    env: TOXENV=lint
install:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install .; fi
  - pip install tox tox-travis
script: tox
after_success:
  - pip install pytest pytest-asyncio coveralls
  - coverage run --source=forge setup.py test
  - coveralls